Added requestData to get results from BQ tables
ccmbenchmark/bigquery-bundle pull request #13
Opened 2021-11-25 09:05 UTC by mdemauroy

2021-11-25 09:14 UTC, xavierleune requested changes
Great ! A few typo to fix but this looks good to me

2021-11-25 09:14 UTC, xavierleune commented on README.md
> +### Working with UnitOfWorl service
Typo: `UnitOfWork`

2021-11-25 09:14 UTC, xavierleune commented on README.md
> +class myDataSource implements DataSourceInterface
`DataSourceInterface` does not belongs to this project, it shoud not be referenced in this example

2021-11-25 09:14 UTC, xavierleune commented on src/BigQueryBundle/BigQuery/UnitOfWork.php
> +use Google_Service_Bigquery_QueryRequest;
The clients now offers a proper namespace, can you rely on `Google\Service\BigQuery\QueryRequest` (double check this name) instead ?

2021-11-25 10:03 UTC, mdemauroy commented on README.md
> +### Working with UnitOfWorl service
Already fixed ^^

2021-11-29 22:11 UTC, xavierleune approved these changes

2021-11-29 22:11 UTC, merged